"""Stage E: ISBN振り直し(slug-volume-final.tsv)を data/manga.v2 へ適用する後処理パス。
★promote + _slug-apply-recluster の後に毎回実行(promoteは振り直しを関知しない)。

  1. recluster TSV の ISBN は recluster ページが正 → volume-final 行を SUPERSEDED skip
  2. 行き先ページ未生成 → ソースページ(現在その ISBN を持つページ)を clone して生成
     (= enrich 済みメタを継承、 volumes だけ対象分。 魔法科14ページ等)
  3. volume dict を source → target へ移動(edition は type+imprint 一致に挿入、 無ければ複製)
  4. 空 edition / 空ページを清掃。 ページ消滅時は alias 行を .cache/stagee-aliases.tsv に出力
  5. 検証: 全行の ISBN が target に居ることを確認して報告

usage: python _apply-volume-moves.py [--dry]
"""
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.stdout.reconfigure(encoding="utf-8")
csv.field_size_limit(10**7)
ROOT = Path(__file__).resolve().parent.parent
V2 = ROOT / "data" / "manga.v2"
DRY = "--dry" in sys.argv

try:
    from yaml import CSafeLoader as _L
except ImportError:
    from yaml import SafeLoader as _L


def load(p):
    return yaml.load(p.read_text(encoding="utf-8"), Loader=_L)


def save(p, d):
    with p.open("w", encoding="utf-8") as f:
        f.write("# Regenerated by scripts/_apply-volume-moves.py (= Stage E ISBN振り直し)\n")
        yaml.dump(d, f, allow_unicode=True, sort_keys=False, default_flow_style=False)


def norm(i):
    return str(i or "").replace("-", "")


def main():
    rows = list(csv.DictReader((ROOT / "data/seeds/slug-volume-final.tsv").open(encoding="utf-8"), delimiter="\t"))
    recl_isbns = set()
    for r in csv.DictReader((ROOT / "data/seeds/slug-recluster-candidates.tsv").open(encoding="utf-8"), delimiter="\t"):
        for i in (r.get("isbns") or "").split(","):
            if i.strip():
                recl_isbns.add(norm(i))

    # 対象 ISBN → target slug(recluster優先で supersede)
    want = {}
    st = defaultdict(int)
    for r in rows:
        i = norm(r["isbn13"])
        if not i:
            continue
        if i in recl_isbns:
            st["superseded_by_recluster"] += 1
            continue
        if (r.get("rekey") or "").startswith(("REVIEW", "UNRESOLVED")):
            st["skipped_flagged"] += 1
            continue
        want[i] = r["final_slug"]

    # v2 索引: isbn → (path, page, ed_idx, vol_idx)
    print("v2 索引構築中...")
    loc = {}
    pages = {}
    for p in list(V2.glob("*.yml")) + list(V2.glob("*.yml.adult")):
        d = load(p)
        if not d:
            continue
        slug = d.get("slug") or p.name.split(".yml")[0]
        pages[slug] = (p, d)
        for ei, ed in enumerate(d.get("editions") or []):
            for vi, v in enumerate(ed.get("volumes") or []):
                i = norm(v.get("isbn13"))
                if i:
                    loc.setdefault(i, (slug, ei, vi))

    moves = defaultdict(list)   # (src_slug, tgt_slug) -> [isbn]
    for i, tgt in want.items():
        cur = loc.get(i)
        if cur is None:
            st["isbn_not_found"] += 1
            continue
        if cur[0] == tgt:
            st["already_ok"] += 1
            continue
        moves[(cur[0], tgt)].append(i)

    print(f"前提: {dict(st)} / 移動対象ペア {len(moves)} / 移動ISBN {sum(len(v) for v in moves.values())}")

    created, deleted, moved = [], [], 0
    alias_rows = []
    touched = set()
    for (src, tgt), isbns in sorted(moves.items()):
        if src not in pages:
            st["src_missing"] += len(isbns)
            continue
        sp, sd = pages[src]
        # target 確保(無ければ source clone)
        if tgt not in pages:
            nd = {k: v for k, v in sd.items() if k != "editions"}
            nd["slug"] = tgt
            nd["editions"] = []
            tp = V2 / (sp.name.replace(src, tgt, 1) if sp.name.startswith(src) else tgt + ".yml")
            tp = V2 / (tgt + (".yml.adult" if sp.name.endswith(".adult") else ".yml"))
            pages[tgt] = (tp, nd)
            created.append(tgt)
        tp, td = pages[tgt]
        iset = set(isbns)
        for ed in list(sd.get("editions") or []):
            take = [v for v in (ed.get("volumes") or []) if norm(v.get("isbn13")) in iset]
            if not take:
                continue
            ed["volumes"] = [v for v in ed["volumes"] if norm(v.get("isbn13")) not in iset]
            # 受け側 edition: type+imprint 一致 or 複製
            dst = None
            for e2 in td.get("editions") or []:
                if e2.get("type") == ed.get("type") and e2.get("imprint") == ed.get("imprint"):
                    dst = e2
                    break
            if dst is None:
                dst = {k: v for k, v in ed.items() if k != "volumes"}
                dst["volumes"] = []
                td.setdefault("editions", []).append(dst)
            dst["volumes"].extend(take)
            moved += len(take)
        sd["editions"] = [e for e in (sd.get("editions") or []) if e.get("volumes")]
        touched.add(src)
        touched.add(tgt)
        if not sd["editions"]:
            deleted.append(src)
            # 消滅ページ → 最多移動先へ alias
            alias_rows.append((src, tgt))

    # 受け側 volumes を番号/日付で安定ソート
    for slug in touched:
        _, d = pages[slug]
        for ed in d.get("editions") or []:
            ed["volumes"].sort(key=lambda v: (v.get("number") if isinstance(v.get("number"), int) else 10**9,
                                              str(v.get("release_date") or "")))

    print(f"移動 {moved} ISBN / ページ生成 {len(created)} / ページ消滅 {len(deleted)}")
    for c in created:
        print("  CREATE:", c)
    for d_ in deleted:
        print("  DELETE:", d_)

    if DRY:
        print("(dry-run: 書き込みなし)")
        return

    for slug in touched:
        p, d = pages[slug]
        if slug in deleted:
            p.unlink(missing_ok=True)
        else:
            save(p, d)
    with (ROOT / ".cache/stagee-aliases.tsv").open("w", encoding="utf-8") as f:
        f.write("old\tnew\n")
        for o, n in alias_rows:
            f.write(f"{o}\t{n}\n")

    # 検証
    bad = 0
    loc2 = {}
    for slug, (p, d) in pages.items():
        if slug in deleted:
            continue
        for ed in d.get("editions") or []:
            for v in ed.get("volumes") or []:
                loc2[norm(v.get("isbn13"))] = slug
    for i, tgt in want.items():
        if i in loc2 and loc2[i] != tgt:
            bad += 1
    print(f"★検証: 位置不一致 {bad}(0が正)/ alias {len(alias_rows)}件 → .cache/stagee-aliases.tsv")


if __name__ == "__main__":
    main()
