#!/usr/bin/env python3
"""
方法D = 直接パッチ。 seed(genre-rakuten.yml / tag-rakuten.yml)を本番 manga.v2 の
**該当作の genres/tags 欄だけ**に純粋追加する(promote を通さない surgical 反映)。

promote と同一条件を再現:
- genres: その作が **trusted空(genres_provisional=True または genres==['other'])** の時だけ上書き。
  → trusted(AniList/Wiki)作には絶対触れない。 genres_rakuten=True を立て genres_provisional を除去。
- tags: 既存 tag 名と重複しないものだけ {category:"Rakuten", rank:60} で追加。

安全策: 触る前に該当ファイルだけ .cache にバックアップ(manga.v2 は git 非追跡のため)。
round-trip 忠実性は検証済(load+dump で他フィールドは不変)。
"""
import json, sys, shutil, io, time
from pathlib import Path
from collections import Counter

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent.parent
MANGA = ROOT / "data" / "manga.v2"
SEEDS = ROOT / "data" / "seeds"
DRY = "--dry-run" in sys.argv

import yaml
try:
    from yaml import CSafeLoader as Loader
except ImportError:
    from yaml import SafeLoader as Loader

MASTER = set(yaml.safe_load((ROOT / "data" / "genres.yml").read_text(encoding="utf-8")).keys())
DEFAULT_HDR = "# Regenerated by scripts/_promote-bulk-v2.py (= path B' step G)"


def load_seed(fn, key):
    p = SEEDS / fn
    out = {}
    for e in (yaml.safe_load(p.read_text(encoding="utf-8")) or {}).get("additions", []):
        if e.get("slug"):
            out[e["slug"]] = e.get(key) or []
    return out


def dump_yaml(d, header):
    buf = io.StringIO()
    buf.write(header.rstrip("\n") + "\n")
    yaml.dump(d, buf, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return buf.getvalue()


def main():
    g_seed = load_seed("genre-rakuten.yml", "genres")
    t_seed = load_seed("tag-rakuten.yml", "tags")
    affected = sorted(set(g_seed) | set(t_seed))
    print(f"seed: genre {len(g_seed):,} / tag {len(t_seed):,} / 影響作 union {len(affected):,}{' [DRY]' if DRY else ''}", flush=True)

    bak = None
    if not DRY:
        bak = ROOT / ".cache" / f"manga.v2.bak-genre-rakuten-{time.strftime('%Y%m%d-%H%M%S')}"
        bak.mkdir(parents=True, exist_ok=True)

    st = Counter()
    gc = Counter(); tc = Counter()
    missing = []
    for slug in affected:
        fp = MANGA / f"{slug}.yml"
        if not fp.exists():
            missing.append(slug); st["file_missing"] += 1; continue
        raw = fp.read_text(encoding="utf-8")
        header = raw.split("\n", 1)[0] if raw.startswith("#") else DEFAULT_HDR
        d = yaml.load(raw, Loader=Loader)
        if not isinstance(d, dict):
            st["parse_fail"] += 1; continue

        changed = False
        # --- genres(trusted空のみ)---
        if slug in g_seed:
            is_trusted_empty = bool(d.get("genres_provisional")) or (d.get("genres") == ["other"])
            if is_trusted_empty:
                gs = {g for g in g_seed[slug] if g in MASTER}
                if gs & {"baseball", "soccer"}:
                    gs.add("sports")
                if gs:
                    d["genres"] = sorted(gs)
                    d["genres_rakuten"] = True
                    d.pop("genres_provisional", None)
                    changed = True
                    st["genre_applied"] += 1
                    for g in gs:
                        gc[g] += 1
            else:
                st["genre_skip_trusted"] += 1   # drift防御: trustedになっていたら触らない

        # --- tags(dedup追加)---
        if slug in t_seed:
            existing = {t.get("name") for t in (d.get("tags") or [])}
            add = [{"name": n, "category": "Rakuten", "rank": 60}
                   for n in t_seed[slug] if n not in existing]
            if add:
                d["tags"] = (d.get("tags") or []) + add
                changed = True
                st["tag_applied"] += 1
                for t in add:
                    tc[t["name"]] += 1

        if changed and not DRY:
            shutil.copy2(fp, bak / fp.name)          # 触る前にバックアップ
            fp.write_text(dump_yaml(d, header), encoding="utf-8")

    print(f"\n=== 方法D 反映{'(DRY)' if DRY else ''} ===", flush=True)
    print(f"genres 上書き: {st['genre_applied']:,}(trusted化で skip: {st['genre_skip_trusted']:,})", flush=True)
    print(f"  genre別: " + ", ".join(f"{k}:{c}" for k, c in gc.most_common()), flush=True)
    print(f"tags 追加: {st['tag_applied']:,}", flush=True)
    print(f"  tag別(上位15): " + ", ".join(f"{k}:{c}" for k, c in tc.most_common(15)), flush=True)
    if missing:
        print(f"  ファイル無し(drop等): {len(missing)}", flush=True)
    if not DRY:
        print(f"backup → {bak}", flush=True)


if __name__ == "__main__":
    main()
