"""data/slug-aliases.yml → ①public/_redirects ②.cache/redirects.json 生成。

★2026-08-14 全面改訂(記憶 redirect_layer_inactive): 旧出力はルート直下 `/旧 /新` 形状で、
  漫画頁の実URLは `/manga/<slug>` のため 301 がどこにも届いていなかった。以後は両出力とも
  `/manga/<旧> → /manga/<新>` 形状に固定する。

①public/_redirects = Cloudflare Pages(preview=mangal-preview)用ネイティブ301。build時 out/ に継承。
  ★Pages の静的redirect上限=2,000行(超過分は無視される)。previewはsubset環境なので
    部分カバーで許容=煙テスト用。本番の全件カバーは②が担う。
②.cache/redirects.json = 本番Worker(workers/r2-serve.js)が KV `REDIRECTS` の
  key `redirects.json` から読む {"/manga/旧": "/manga/新"} の全件map。
  KV投入 = `python scripts/_kv-redirects-sync.py`(週次蒸留 手順4の後)。
"""
import json
import re
from pathlib import Path

ALIAS = Path("data/slug-aliases.yml")
OUT = Path("public/_redirects")
OUT_JSON = Path(".cache/redirects.json")


def main() -> None:
    aliases: dict[str, str] = {}
    for line in ALIAS.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^(\S+):\s*(.+)$", line)
        if m and not line.startswith("#"):
            aliases[m.group(1)] = m.group(2).strip()

    # ★連鎖の平坦化(2026-08-17 GSC検証で発見: 1997→ochi-1994→ochi の2段301):
    #   yml は来歴として連鎖のまま残し、出力側だけ最終宛先へ畳んで1ホップにする。
    def _resolve(k: str, limit: int = 10) -> str:
        seen, cur = set(), aliases[k]
        while cur in aliases and cur not in seen and limit > 0:
            seen.add(cur)
            cur = aliases[cur]
            limit -= 1
        return cur

    aliases = {k: _resolve(k) for k in aliases}

    # ★不変条件の検算(2026-09-05 実踏): 生成物を見ないと気付けない2型を必ず数える。
    #   A. alias のキーが公開slug = **生きた頁を404へ飛ばす**(slow-loop -> surooruupu で実踏)
    #   B. 平坦化後の宛先が未公開  = 301の先が404
    #   改名すると以前の逆向きaliasが残って A になる。改名作業のたびにここで気付けるようにする。
    try:
        import json as _json
        _idx = _json.loads(Path('data/manga-list-index.json').read_text(encoding='utf-8'))
        _si = _idx['f'].index('slug')
        _pub = {r[_si] for r in _idx['d']}
        _hijack = [k for k in aliases if k in _pub]
        _dead = [k for k, v in aliases.items() if v not in _pub]
        if _hijack:
            print('  ' + '\u2605' + 'WARN alias のキーが公開slug %d件(生きた頁を飛ばす): %s'
                  % (len(_hijack), ', '.join(_hijack[:5])))
        if _dead:
            print('  ' + '\u2605' + 'WARN 301の宛先が未公開 %d件: %s'
                  % (len(_dead), ', '.join(_dead[:5])))
        if not _hijack and not _dead:
            print('  OK  リダイレクト健全(キー衝突0 / 宛先未公開0)')
    except Exception as _e:
        print('  (リダイレクト検算skip: %s)' % _e)

    lines = [
        "# Auto-generated by scripts/_gen-redirects.py from data/slug-aliases.yml",
        "# 旧 slug → 新 slug の 301(漫画頁は /manga/ 配下=この形状以外は届かない)",
        "# ★Cloudflare Pages は静的redirect上限2,000行(preview=部分カバー)。本番全件は KV REDIRECTS 側。",
        "",
    ]
    for old in sorted(aliases):
        new = aliases[old]
        lines.append(f"/manga/{old} /manga/{new} 301")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote: {OUT} ({len(aliases)} redirects)")

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    kv_map = {f"/manga/{old}": f"/manga/{new}" for old, new in aliases.items()}
    OUT_JSON.write_text(json.dumps(kv_map, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"wrote: {OUT_JSON} ({len(kv_map)} entries, KV投入= python scripts/_kv-redirects-sync.py)")


if __name__ == "__main__":
    main()
