"""data/slug-aliases.yml → public/_redirects (= Cloudflare Pages 301 redirect 設定) 生成。

Cloudflare Pages docs: https://developers.cloudflare.com/pages/configuration/redirects/
形式: /旧 path /新 path 301
build 時 out/_redirects に コピーされ、 Cloudflare Edge で 自動適用。
"""
import re
from pathlib import Path

ALIAS = Path("data/slug-aliases.yml")
OUT = Path("public/_redirects")


def main() -> None:
    aliases: dict[str, str] = {}
    for line in ALIAS.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^(\S+):\s*(.+)$", line)
        if m:
            aliases[m.group(1)] = m.group(2).strip()

    lines = [
        "# Auto-generated by scripts/_gen-redirects.py from data/slug-aliases.yml",
        "# Cloudflare Pages 301 redirect: 旧 slug → 新 slug",
        "",
    ]
    for old in sorted(aliases):
        new = aliases[old]
        lines.append(f"/{old} /{new} 301")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote: {OUT} ({len(aliases)} redirects)")


if __name__ == "__main__":
    main()
